<?php
return [
    'permission' => array(
        'users',
        'roles',
        'brands',
        'product-category',
        'tax',
        'coupon',
        'discount',
        'email-template',
        'video-booking',
        'walkthroughs',
        'testimonials',
        'main_category',
        'pincode',
        'city',
        'state',
        'country',
        'order-status',
        'order-cancel',
        'cancel-requested',
        'sms-template',
        'payment-gateway',
        'customer',
        'banner',
        'products',
        'product-attribute',
        'product-collection',
        'product-tags',
        'product-labels',
        'reports',
        'sub_category',
        'global',
        'my-profile',
        'newsletter',
        'quick-link',
        'bulkUpload',
        'request_details'

    ),

];
